### ISSUE TITLE
unicode errors w/ some versions of python

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#440]
Unicode characters can cause errors with some versions of pythons / operating systems. One such character is: `' – '`

We have an integration test for this already, but it seems to pass on circle and appveyor. I _think_ it has to do with python 3.5

**Comment by drewbanin** [comment]
This also happens with `dbt seed` on python 36 -- it's not just a py2 / py35 issue.

```
>dbt seed
Encountered an error:
'utf-8' codec can't decode byte 0x80 in position 339: invalid start byte
```

Using `Python 3.6.3 :: Anaconda, Inc.`

**Comment by drewbanin** [comment]
Another one, this time from Sinter:

```
....
File "/usr/local/lib/python3.5/dist-packages/dbt/compat.py", line 45, in write_file
return f.write(to_string(s))
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 873: ordinal not in range(128)
```

**Comment by sphinks** [comment]
Any idea how to workaround it? I get this issue on Fedora 26: 'ascii' codec can't decode byte 0xd0 in position 16: ordinal not in range(128)
I can not find out what symbol cause this error. I have Python 2.7 and 3.6 but I'm not sure version dbt is using. How can I switch version of python for dbt?

**Comment by drewbanin** [comment]
Hey @sphinks - I think this would only be an issue in python 2.7, and python 3.6 should be able to handle the non-ascii chars just fine. You can install dbt into a virtualenv using python3 -- there's some more info on how to do that [here](https://packaging.python.org/guides/installing-using-pip-and-virtualenv)

In the short term, I think you can just grep for non-ascii characters in your project, and remove them manually. If you're on Fedora, I think this will work:

```bash
grep --color='auto' -P -rn '[^\x00-\x7F]' models/ data/
```

**Comment by sphinks** [comment]
@drewbanin It is strange, but 
`grep --color='auto' -P -rn '[^\x00-\x7F]' models/ data/`
does not find any non ascii char. Seem like it is a bug of some combination of asci chars or something else.

**Comment by drewbanin** [comment]
@sphinks do you have any other dbt directories? Like maybe the `tests/` dir or the `analysis/` dir or something? You can add those to the end of the command above. I'd be really surprised if there aren't actually any nonascii chars in any of your dbt dirs!

**Comment by sphinks** [comment]
@drewbanin no, I only my test project in model folder. I have found point of issue:
In case I put in source code of model such code:
'''select
    subscription_id,
    status,
    date,
    to_char("date", 'YYYYMM') as yearMonth,
    row_number() over (
        PARTITION BY 
        subscription_id
    ) as subscription_id_rank
from table_a'''

I get working model, in case I add to `PARTITION BY` another field like this `PARTITION BY 
        subscription_id, yearMonth` I get an ascii error. It is blowing my mind now. :)

**Comment by sphinks** [comment]
@drewbanin it is really funny, but in case I run the same code with python 3 I get a clear sql error, relating to problems with yearMonth field, once I fixed it, it runs perfectly. Meanwhile with python 2 I get ascii error instead of sql error, but once I fixed an issue with a yearMonth field, it run perfectly with python 2 too.

**Comment by drewbanin** [comment]
Going to close this issue, but we can reopen if folks are still having issues. I think we can chalk this up to old/unsupported versions of python (like 2.x and 3.5, for instance).

**Comment by shubham-espbi** [comment]
I am encountering same error - 'utf-8' codec can't decode byte 0xe3 in position 1188: invalid continuation byte. Is there a fix to this?

**Comment by lansdell-hs** [comment]
This is a problem I'm continuously running into when using codegen generate_base_model. The model is being generated from a table, so it's not an input file I need to clean.

**Comment by jtcohen6** [comment]
@lansdell-hs Are you seeing this same error?
```
'utf-8' codec can't decode byte 0x80 in position 339: invalid start byte
```
I'm not sure how `codegen` would be putting a non-ascii character in your compiled model file, but it could be an issue with the package, or when moving / copy-pasting the compiled result into a new model file.

**Comment by lansdell-hs** [comment]
I'm seeing the same thing except it says 'position 0'. I'm not copying and
pasting anything, but I am routing the output of the command to a .sql file
